name: WP Plugin Check
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
    - master
    - dev
    - 'releases/*'
  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

jobs:
  # Runs the WP Plugin Check.
  #
  # Checks from the Plugin Review Team.
  #
  # For the detailed list of checks:
  # - https://wordpress.org/plugins/plugin-check/
  #
  # Performs the following steps:
  # - Checks out the repository.
  # - Sets up PHP.
  # - Installs Composer dependencies.
  # - Runs the Plugin Check.
  plugin-check:
    name: Plugin Check
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up PHP
      uses: shivammathur/setup-php@2.33.0
      with:
        php-version: '7.4'
        coverage: none
      env:
        fail-fast: false

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Install Composer dependencies
      uses: ramsey/composer-install@v3
      with:
        composer-options: "--no-dev"

    - name: Copy the plugin files to the plugin check folder, excluding the files on .distignore.
      run: rsync -rc --exclude-from="$GITHUB_WORKSPACE/.distignore" "$GITHUB_WORKSPACE/" translation-stats/ --delete --delete-excluded

    - name: Run plugin check
      uses: wordpress/plugin-check-action@v1
      with:
        build-dir: 'translation-stats'
        exclude-directories: 'translation-stats/assets/lib'
